name: CI

on:
  pull_request:
  push:
    branches: ['main']

env:
  RUSTFLAGS: "-D warnings"

jobs:
  test:
    name: Test Suite
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Check build
        run: cargo check --locked --workspace --all-targets
      - name: Run tests
        run: cargo test --locked --workspace
