name: CI

on:
  pull_request:
  push:
    branches:
    - 'main'

jobs:
  test:
    name: Test Suite
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Check build
        run: RUSTFLAGS="-D warnings" cargo check --locked
